  # action.yaml
name: "Perform asdf"
description: "User asdf as package manager to install everything"
inputs:
  pokemon_id:
    description: "number of the pokemon in the pokedex"
    required: true
    default: "1"
outputs:
  pokemon_name:
    description: "Name des Pokemons"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.pokemon_id}}
