name: Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: asdf-vm/asdf
          path: .asdf
          ref: 'v0.8.1'
      - name: install plugin
        uses: pratikbalar/perform-asdf
        with:
          these: |
            terraform 1.0.6 https://github.com/asdf-community/asdf-hashicorp.git
            java openjdk-10 https://github.com/halcyon/asdf-java.git

      - name: test installations
        run: |
          terraform --version
          java -version
