name: Release

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: asdf-vm/asdf
          path: .asdf
          ref: 'v0.8.1'
      - name: install plugin
        uses: ./
        with:
          these: |
            terraform 1.0.6 https://github.com/asdf-community/asdf-hashicorp.git
            golang 1.16.8 https://github.com/kennyp/asdf-golang.git

      - name: test installations
        run: |
          . .asdf/asdf.sh
          terraform --version
          go version
